spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true #system.out.println을 통해서 나오기떄문에 주석 운영에서는 사용X
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace